apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: myapp
spec:
  #schedulerName: my-scheduler ##scheduler personalizado
  containers:
    - name: nginx 
      image: nginx:1.18
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
  nodeName: #Campo que te indica en que Node deseas enviar un pod
