apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    app: myapp
spec:
  strategy:
    rollingUpdate:
      #availableReplicas=replicas-maxUnavailable
      maxUnavailable: 2 #numero maximo de pods que no estaran disponible ante un nuevo despliegue 
      maxSurge: 2 # numero adicionales a la replicas establecidas por el deploy 
  #necesita que se vuelva a redesplegar
  revisionHistoryLimit: 1 #Numero de Rs que puede tener el historial, borra el historial de rs en un deploy
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template: 
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx 
          image: nginx
    