apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  #necesita que se vuelva a redesplegar
  revisionHistoryLimit: 1 #Numero de Rs que puede tener el historial, borra el historial de rs en un deploy
  selector:
    matchLabels:
      app: myapp
  replicas: 6
  template: 
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx 
          image: nginx