apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
  nodeSelector:
    size: Large # es la etiqueta que se le coloca al nodo k label nodes node-1 size=Large, no se permite or, and o not
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In # Valid operators are In,NotIn, Exists, DoesNotExist. Gt, and Lt.
              values:
                - "Large"
                - "Medium"

 