apiVersion: v1
kind: Service
metadata: 
  name: back-end
spec:
  type: ClusterIP
  ports:
   - targetPort: 80 #el puerto que expone el contenedor en caso de no declarar un puerto este toma el mismo del port
     port: 80 #puerto de comunicacion entre el svc y el pod, este valor es obligatorio
     protocol: TCP # por defect es TCP pero puede ser supported values: "SCTP", "TCP", "UDP"
  selector:
    app: myapp  
    tier: frontend     
  