apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: myapp
spec:
  volumes:
    - name: app-secret-volume # esto se crea como un archivo en /opt/app-secret-volume sin base
      secret:
        secretName: app-secret ## montar un secret como volumen
  containers:
    - name: nginx 
      image: nginx:1.18
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      env:
        - name: APP_COLOR ## como variable de entorno en secret
          valueFrom:
            secretKeyRef :
              key: app-secret
              name: APP_COLOR
      envFrom: # como archivo de secret
        - secretRef :
            name: app-secret
       