#As of kubernetes 1.19, the API to use for CSR is certificates.k8s.io/v1. Please note that an additional field called signerName should also be added when creating CSR.
#For client authentication to the API server we will use the built-in signer kubernetes.io/kube-apiserver-client.
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbUZ1WlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUx3L1E0NjNuTWxrQ3g4MG4wdXRFMFpMcllTRjJBNktuTm15eDIzb29OaDRrS3I0ClRwYitaMXpaYm1DZ1Bneno0a2w0YUJrRWVLdFRQTC9jcG5ZcXBFamVZZGdJU21OdXFrcC9UMUUySXJ2TlNORzEKL0RUMGI4bVdtcGZpZ2pCZi9QNTlhUStkMzNIWmo2b3AxVWdiem5wWWN5eldmOHA3cFUzZlNod2J6ZVFnb3ZCSgo4bEk0RDFFckVITjlmdXpiS3lhZnlCWFdFcHJFOTk1b1ZpTGJ3ZXM5M29Jdko1MjlpMWdKbld6Qk05MU1qZ3o2CmhJdkNzeUpITlFBUTVWeU1Udmg3VC9Wa2xWRWR2c3p4VHNpOWJMc2h3TlVuTE8xbENvWTdBaElYczZYUFJCSmIKWWgrSVV5cmF1RGViRFg3bkdSVmxUdk1lQ21ZNnFYQ1BUTnRNL2lVQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQnZZVndOaTNGU3FmN3JTZjYzd0lSNDMwdno2Y0RFQU55RzNVcVRjYU5tLzZBL0RpVmx2WjhSCk5qU3JsRCtHNSsrNXhkTERpK0lQay96TEpxVVNRaENFNTBtenc0SThKeTdVSzMrZVkxTDJZeE92QTVocEk0V0MKd1RHQlZGbjAra2ZyZHE4cDdIZVhnZWYvejJiMm5SOHVwQXNTSHJXUTBsaVdtQUFiNW5UOEhXMjFxdFFZQ0FnMwp1b1JSWGpZd21RRURnaDB3QUxHT1Y3MjZDeGJJanhpVlNUeEMwVnFOa3lLR2RoRjcwVmxPRThsZzluUnVaZXluCjcxZkl0NnNGVldyeTBRL292U2dRL3ZGMWZGZzRzeVhwVlFkSFBySXZiaFdIMlpEYmF4TU9iN2JRZnlSRitqbjcKWUZIUW1xUC9GUXpxUHIwRmFnclFzeVVWRjkwRExmL3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  usages:
  - digital signature
  - key encipherment
  - client auth