#As of kubernetes 1.19, the API to use for CSR is certificates.k8s.io/v1. Please note that an additional field called signerName should also be added when creating CSR.
#For client authentication to the API server we will use the built-in signer kubernetes.io/kube-apiserver-client.
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jonathan
spec:
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400 # one day
  groups:
    - system:authenticated
  #aqui debe ir el csr del certificado
  request: 
  usages:
    - digital signature
    - key encipherment
    - client auth
