apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  sessionAffinity: ClientIP # siempre va al mismo pod por un tiempo de 10800 min o 3 horas
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1  #timeout de la conexion por defecto  tiempo de 10800 min o 3 horas esto funciona cuando se  tiene un cluster no en minikube
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: voting-app-pod
    app: demo-voting-app  