apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: monitoring-daemon
  labels:
    app: monitoring-daemon
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template: 
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name:  nginx 
          image:  nginx
    