apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  labels: 
    app: webapp
    tier: frontend
  name: webapp
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      tier: frontend
  template: 
    metadata: 
      labels: 
        tier: frontend
    spec: 
      containers: 
        - 
          image: nginx
          name: webapp
